/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\小曌-知识库【2022】\\1022-blog\\myblog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7ea10cda",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ea10cda").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-a902958a",
    path: "/blogs/category1/2018/20180122.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a902958a").then(next)
    },
  },
  {
    name: "v-edf9274a",
    path: "/blogs/category1/2018/20180107.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edf9274a").then(next)
    },
  },
  {
    name: "v-429c9e4a",
    path: "/blogs/category1/2018/20180213.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-429c9e4a").then(next)
    },
  },
  {
    name: "v-f658b74a",
    path: "/blogs/category1/2018/20180921.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f658b74a").then(next)
    },
  },
  {
    name: "v-0c49a08a",
    path: "/blogs/category1/2018/20180816.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c49a08a").then(next)
    },
  },
  {
    name: "v-33fd7f0a",
    path: "/blogs/category1/2018/20180612.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33fd7f0a").then(next)
    },
  },
  {
    name: "v-f01d9cca",
    path: "/blogs/category1/2018/20181021.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f01d9cca").then(next)
    },
  },
  {
    name: "v-89b7a58a",
    path: "/blogs/category1/2018/20181112.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89b7a58a").then(next)
    },
  },
  {
    name: "v-0fc6f4bb",
    path: "/blogs/category1/2018/20181215.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fc6f4bb").then(next)
    },
  },
  {
    name: "v-b383dd0a",
    path: "/blogs/category1/2018/20181220.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b383dd0a").then(next)
    },
  },
  {
    name: "v-a3c97e0a",
    path: "/blogs/category1/2019/20190124.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a3c97e0a").then(next)
    },
  },
  {
    name: "v-a7f7e70a",
    path: "/blogs/category1/2019/20190216.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7f7e70a").then(next)
    },
  },
  {
    name: "v-1398ae4a",
    path: "/blogs/category1/2019/20190422.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1398ae4a").then(next)
    },
  },
  {
    name: "v-0f6a454a",
    path: "/blogs/category1/2019/20190330.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f6a454a").then(next)
    },
  },
  {
    name: "v-952a5eca",
    path: "/blogs/category1/2019/20190523.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-952a5eca").then(next)
    },
  },
  {
    name: "v-41934eca",
    path: "/blogs/category1/2019/20190622.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41934eca").then(next)
    },
  },
  {
    name: "v-7cfdb47b",
    path: "/blogs/category1/2019/20190711.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cfdb47b").then(next)
    },
  },
  {
    name: "v-1bf6df4a",
    path: "/blogs/category1/2019/20190921.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bf6df4a").then(next)
    },
  },
  {
    name: "v-eae4854a",
    path: "/blogs/category1/2019/20191023.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eae4854a").then(next)
    },
  },
  {
    name: "v-1eeda59b",
    path: "/blogs/category1/2019/20191120.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1eeda59b").then(next)
    },
  },
  {
    name: "v-de5b760a",
    path: "/blogs/category1/2019/20191202.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de5b760a").then(next)
    },
  },
  {
    name: "v-691d7c7b",
    path: "/blogs/category1/2019/20191228.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-691d7c7b").then(next)
    },
  },
  {
    name: "v-62db90fb",
    path: "/blogs/category1/2020/20200102.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62db90fb").then(next)
    },
  },
  {
    name: "v-393dd60a",
    path: "/blogs/category1/2020/20200212.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-393dd60a").then(next)
    },
  },
  {
    name: "v-c330a6ca",
    path: "/blogs/category1/2019/20191227.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c330a6ca").then(next)
    },
  },
  {
    name: "v-02b9ac5b",
    path: "/blogs/category1/2020/20200316.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02b9ac5b").then(next)
    },
  },
  {
    name: "v-76b4d0bb",
    path: "/blogs/category1/2020/20200621.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76b4d0bb").then(next)
    },
  },
  {
    name: "v-ac30674a",
    path: "/blogs/category1/2020/20200712.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac30674a").then(next)
    },
  },
  {
    name: "v-5867f0db",
    path: "/blogs/category1/2020/20200422.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5867f0db").then(next)
    },
  },
  {
    name: "v-931ba80a",
    path: "/blogs/category1/2020/20200517.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-931ba80a").then(next)
    },
  },
  {
    name: "v-00a1c85b",
    path: "/blogs/category1/2020/20200723.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00a1c85b").then(next)
    },
  },
  {
    name: "v-2a6d505b",
    path: "/blogs/category1/2020/20200822.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a6d505b").then(next)
    },
  },
  {
    name: "v-267bf54a",
    path: "/blogs/category1/2020/20201023.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-267bf54a").then(next)
    },
  },
  {
    name: "v-ef10e90a",
    path: "/blogs/category1/2020/20200917.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ef10e90a").then(next)
    },
  },
  {
    name: "v-0d2619bb",
    path: "/blogs/category1/2020/20201130.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d2619bb").then(next)
    },
  },
  {
    name: "v-1dddcc7b",
    path: "/blogs/category1/2020/20201206.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1dddcc7b").then(next)
    },
  },
  {
    name: "v-2fd6558a",
    path: "/blogs/category1/2021/20210122.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fd6558a").then(next)
    },
  },
  {
    name: "v-5c10a91b",
    path: "/blogs/category1/2021/20210112.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c10a91b").then(next)
    },
  },
  {
    name: "v-076d6c9b",
    path: "/blogs/category1/2021/20210226.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-076d6c9b").then(next)
    },
  },
  {
    name: "v-52202588",
    path: "/docs/Nuxt/asyncData.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52202588").then(next)
    },
  },
  {
    name: "v-0b0ee53b",
    path: "/blogs/category1/2020/20201222.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b0ee53b").then(next)
    },
  },
  {
    name: "v-470d3ee2",
    path: "/docs/Vue/animationClass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-470d3ee2").then(next)
    },
  },
  {
    name: "v-a96ef760",
    path: "/docs/Nuxt/introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a96ef760").then(next)
    },
  },
  {
    name: "v-1b13faf4",
    path: "/docs/Vue/API.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b13faf4").then(next)
    },
  },
  {
    name: "v-0b2b80f0",
    path: "/docs/Vue/attribute.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b2b80f0").then(next)
    },
  },
  {
    name: "v-c96789fc",
    path: "/docs/Vue/asyncComponent.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c96789fc").then(next)
    },
  },
  {
    name: "v-05ee313c",
    path: "/docs/Vue/Data.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05ee313c").then(next)
    },
  },
  {
    name: "v-951334ec",
    path: "/docs/Vue/directive.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-951334ec").then(next)
    },
  },
  {
    name: "v-ab14dd18",
    path: "/docs/Vue/event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ab14dd18").then(next)
    },
  },
  {
    name: "v-15110702",
    path: "/docs/Vue/ref.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15110702").then(next)
    },
  },
  {
    name: "v-4fc70de2",
    path: "/docs/Vue/funComponent.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fc70de2").then(next)
    },
  },
  {
    name: "v-734e6e16",
    path: "/docs/Vue/renderFun.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-734e6e16").then(next)
    },
  },
  {
    name: "v-d050eb9c",
    path: "/docs/Vue/filters.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d050eb9c").then(next)
    },
  },
  {
    name: "v-01afb9e2",
    path: "/docs/Vue/template.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01afb9e2").then(next)
    },
  },
  {
    name: "v-caae583c",
    path: "/docs/Vue/v-bind.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-caae583c").then(next)
    },
  },
  {
    name: "v-5ed348e2",
    path: "/docs/Vue/slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ed348e2").then(next)
    },
  },
  {
    name: "v-4c87de3c",
    path: "/docs/Vue/v-if&v-for.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c87de3c").then(next)
    },
  },
  {
    name: "v-d0eb3afc",
    path: "/docs/Vue/v-is.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0eb3afc").then(next)
    },
  },
  {
    name: "v-00794244",
    path: "/docs/Vue/v-model.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00794244").then(next)
    },
  },
  {
    name: "v-33f40c28",
    path: "/docs/jottings/DOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33f40c28").then(next)
    },
  },
  {
    name: "v-4bfa42f1",
    path: "/docs/delicacys/%E6%97%A0%E6%B2%B9%E6%8D%9E%E6%B1%81%E7%B2%89%E4%B8%9D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bfa42f1").then(next)
    },
  },
  {
    path: "/docs/delicacys/无油捞汁粉丝.html",
    redirect: "/docs/delicacys/%E6%97%A0%E6%B2%B9%E6%8D%9E%E6%B1%81%E7%B2%89%E4%B8%9D.html"
  },
  {
    name: "v-53c9a668",
    path: "/docs/Nuxt/context.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53c9a668").then(next)
    },
  },
  {
    name: "v-1191e968",
    path: "/docs/jottings/BOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1191e968").then(next)
    },
  },
  {
    name: "v-8beadbb0",
    path: "/docs/jottings/Git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8beadbb0").then(next)
    },
  },
  {
    name: "v-dd1c2730",
    path: "/docs/jottings/HarmonyOS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dd1c2730").then(next)
    },
  },
  {
    name: "v-367c616a",
    path: "/docs/jottings/carousel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-367c616a").then(next)
    },
  },
  {
    name: "v-249c4328",
    path: "/docs/jottings/accordion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-249c4328").then(next)
    },
  },
  {
    name: "v-82391230",
    path: "/docs/jottings/Nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82391230").then(next)
    },
  },
  {
    name: "v-1229e90c",
    path: "/docs/jottings/filter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1229e90c").then(next)
    },
  },
  {
    name: "v-2c9eb9a8",
    path: "/docs/jottings/flexbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c9eb9a8").then(next)
    },
  },
  {
    name: "v-2e46c268",
    path: "/docs/jottings/loading.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e46c268").then(next)
    },
  },
  {
    name: "v-376a1af0",
    path: "/docs/jottings/reset.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-376a1af0").then(next)
    },
  },
  {
    name: "v-20a32ec8",
    path: "/docs/jottings/genealogy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20a32ec8").then(next)
    },
  },
  {
    name: "v-3d2718b4",
    path: "/docs/jottings/mobile.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d2718b4").then(next)
    },
  },
  {
    name: "v-518b0028",
    path: "/docs/jottings/scrollTemp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-518b0028").then(next)
    },
  },
  {
    name: "v-41f90648",
    path: "/docs/jottings/particles.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41f90648").then(next)
    },
  },
  {
    name: "v-3c74571a",
    path: "/docs/jottings/vueBuild.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c74571a").then(next)
    },
  },
  {
    name: "v-0a370a30",
    path: "/docs/jottings/whirligig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a370a30").then(next)
    },
  },
  {
    name: "v-985c8bac",
    path: "/docs/jottings/shadow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-985c8bac").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-e8d965c8",
    path: "/tag/JS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d965c8").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/index.html",
    redirect: "/tag/JS/"
  },
  {
    name: "v-dab8e1c2",
    path: "/tag/Nginx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-dab8e1c2").then(next)
    },
    meta: {"pid":"tags","id":"Nginx"}
  },
  {
    path: "/tag/Nginx/index.html",
    redirect: "/tag/Nginx/"
  },
  {
    name: "v-184d950c",
    path: "/tag/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-184d950c").then(next)
    },
    meta: {"pid":"tags","id":"HTML"}
  },
  {
    path: "/tag/HTML/index.html",
    redirect: "/tag/HTML/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-ec38e77e",
    path: "/tag/Cookie/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-ec38e77e").then(next)
    },
    meta: {"pid":"tags","id":"Cookie"}
  },
  {
    path: "/tag/Cookie/index.html",
    redirect: "/tag/Cookie/"
  },
  {
    name: "v-3248559a",
    path: "/tag/VUE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3248559a").then(next)
    },
    meta: {"pid":"tags","id":"VUE"}
  },
  {
    path: "/tag/VUE/index.html",
    redirect: "/tag/VUE/"
  },
  {
    name: "v-7c44ce15",
    path: "/tag/运算符/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7c44ce15").then(next)
    },
    meta: {"pid":"tags","id":"运算符"}
  },
  {
    path: "/tag/运算符/index.html",
    redirect: "/tag/运算符/"
  },
  {
    path: "/tag/%E8%BF%90%E7%AE%97%E7%AC%A6/",
    redirect: "/tag/运算符/"
  },
  {
    name: "v-3231af64",
    path: "/tag/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3231af64").then(next)
    },
    meta: {"pid":"tags","id":"npm"}
  },
  {
    path: "/tag/npm/index.html",
    redirect: "/tag/npm/"
  },
  {
    name: "v-4bc4e1e0",
    path: "/tag/组件/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4bc4e1e0").then(next)
    },
    meta: {"pid":"tags","id":"组件"}
  },
  {
    path: "/tag/组件/index.html",
    redirect: "/tag/组件/"
  },
  {
    path: "/tag/%E7%BB%84%E4%BB%B6/",
    redirect: "/tag/组件/"
  },
  {
    name: "v-0c1cbc56",
    path: "/tag/正则/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0c1cbc56").then(next)
    },
    meta: {"pid":"tags","id":"正则"}
  },
  {
    path: "/tag/正则/index.html",
    redirect: "/tag/正则/"
  },
  {
    path: "/tag/%E6%AD%A3%E5%88%99/",
    redirect: "/tag/正则/"
  },
  {
    name: "v-d2055fbe",
    path: "/categories/前端小笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-d2055fbe").then(next)
    },
    meta: {"pid":"categories","id":"前端小笔记"}
  },
  {
    path: "/categories/前端小笔记/index.html",
    redirect: "/categories/前端小笔记/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/",
    redirect: "/categories/前端小笔记/"
  },
  {
    name: "v-1f2f3733",
    path: "/categories/问题集中营/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-1f2f3733").then(next)
    },
    meta: {"pid":"categories","id":"问题集中营"}
  },
  {
    path: "/categories/问题集中营/index.html",
    redirect: "/categories/问题集中营/"
  },
  {
    path: "/categories/%E9%97%AE%E9%A2%98%E9%9B%86%E4%B8%AD%E8%90%A5/",
    redirect: "/categories/问题集中营/"
  },
  {
    name: "v-d0fbe166",
    path: "/categories/Cookie/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-d0fbe166").then(next)
    },
    meta: {"pid":"categories","id":"Cookie"}
  },
  {
    path: "/categories/Cookie/index.html",
    redirect: "/categories/Cookie/"
  },
  {
    name: "v-85672be2",
    path: "/categories/排序/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-85672be2").then(next)
    },
    meta: {"pid":"categories","id":"排序"}
  },
  {
    path: "/categories/排序/index.html",
    redirect: "/categories/排序/"
  },
  {
    path: "/categories/%E6%8E%92%E5%BA%8F/",
    redirect: "/categories/排序/"
  },
  {
    name: "v-7f070da7",
    path: "/categories/VUE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f070da7").then(next)
    },
    meta: {"pid":"categories","id":"VUE"}
  },
  {
    path: "/categories/VUE/index.html",
    redirect: "/categories/VUE/"
  },
  {
    name: "v-7efe64ca",
    path: "/categories/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efe64ca").then(next)
    },
    meta: {"pid":"categories","id":"CSS"}
  },
  {
    path: "/categories/CSS/index.html",
    redirect: "/categories/CSS/"
  },
  {
    name: "v-3dfe3db2",
    path: "/categories/Promise/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-3dfe3db2").then(next)
    },
    meta: {"pid":"categories","id":"Promise"}
  },
  {
    path: "/categories/Promise/index.html",
    redirect: "/categories/Promise/"
  },
  {
    name: "v-7f1260c2",
    path: "/categories/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f1260c2").then(next)
    },
    meta: {"pid":"categories","id":"npm"}
  },
  {
    path: "/categories/npm/index.html",
    redirect: "/categories/npm/"
  },
  {
    name: "v-b5983fc8",
    path: "/categories/组件/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-b5983fc8").then(next)
    },
    meta: {"pid":"categories","id":"组件"}
  },
  {
    path: "/categories/组件/index.html",
    redirect: "/categories/组件/"
  },
  {
    path: "/categories/%E7%BB%84%E4%BB%B6/",
    redirect: "/categories/组件/"
  },
  {
    name: "v-75f01a3e",
    path: "/categories/正则/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-75f01a3e").then(next)
    },
    meta: {"pid":"categories","id":"正则"}
  },
  {
    path: "/categories/正则/index.html",
    redirect: "/categories/正则/"
  },
  {
    path: "/categories/%E6%AD%A3%E5%88%99/",
    redirect: "/categories/正则/"
  },
  {
    name: "v-1b8d5889",
    path: "/categories/深夜食堂/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-1b8d5889").then(next)
    },
    meta: {"pid":"categories","id":"深夜食堂"}
  },
  {
    path: "/categories/深夜食堂/index.html",
    redirect: "/categories/深夜食堂/"
  },
  {
    path: "/categories/%E6%B7%B1%E5%A4%9C%E9%A3%9F%E5%A0%82/",
    redirect: "/categories/深夜食堂/"
  },
  {
    name: "v-7f71ddbe",
    path: "/tag/JS/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f71ddbe").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/page/2/index.html",
    redirect: "/tag/JS/page/2/"
  },
  {
    name: "v-d6ece308",
    path: "/categories/前端小笔记/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d6ece308").then(next)
    },
    meta: {"pid":"categories","id":"前端小笔记"}
  },
  {
    path: "/categories/前端小笔记/page/2/index.html",
    redirect: "/categories/前端小笔记/page/2/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/page/2/",
    redirect: "/categories/前端小笔记/page/2/"
  },
  {
    name: "v-d6ece2ca",
    path: "/categories/前端小笔记/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d6ece2ca").then(next)
    },
    meta: {"pid":"categories","id":"前端小笔记"}
  },
  {
    path: "/categories/前端小笔记/page/3/index.html",
    redirect: "/categories/前端小笔记/page/3/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/page/3/",
    redirect: "/categories/前端小笔记/page/3/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]