/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-a902958a",
        "v-429c9e4a",
        "v-0c49a08a",
        "v-33fd7f0a",
        "v-f01d9cca",
        "v-0fc6f4bb",
        "v-a7f7e70a",
        "v-1398ae4a",
        "v-0f6a454a",
        "v-952a5eca",
        "v-41934eca",
        "v-7cfdb47b",
        "v-1bf6df4a",
        "v-62db90fb",
        "v-393dd60a",
        "v-02b9ac5b",
        "v-76b4d0bb",
        "v-5867f0db",
        "v-931ba80a",
        "v-076d6c9b"
      ]
    },
    "Nginx": {
      "key": "Nginx",
      "scope": "tags",
      "path": "/tag/Nginx/",
      "pageKeys": [
        "v-edf9274a"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "tags",
      "path": "/tag/HTML/",
      "pageKeys": [
        "v-f658b74a"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-89b7a58a",
        "v-b383dd0a",
        "v-ac30674a"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "tags",
      "path": "/tag/Cookie/",
      "pageKeys": [
        "v-a3c97e0a"
      ]
    },
    "VUE": {
      "key": "VUE",
      "scope": "tags",
      "path": "/tag/VUE/",
      "pageKeys": [
        "v-eae4854a",
        "v-1eeda59b",
        "v-de5b760a",
        "v-691d7c7b",
        "v-c330a6ca",
        "v-ef10e90a",
        "v-0d2619bb",
        "v-1dddcc7b",
        "v-5c10a91b"
      ]
    },
    "运算符": {
      "key": "运算符",
      "scope": "tags",
      "path": "/tag/运算符/",
      "pageKeys": [
        "v-00a1c85b"
      ]
    },
    "npm": {
      "key": "npm",
      "scope": "tags",
      "path": "/tag/npm/",
      "pageKeys": [
        "v-2a6d505b",
        "v-0b0ee53b"
      ]
    },
    "组件": {
      "key": "组件",
      "scope": "tags",
      "path": "/tag/组件/",
      "pageKeys": [
        "v-267bf54a"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "tags",
      "path": "/tag/正则/",
      "pageKeys": [
        "v-2fd6558a"
      ]
    }
  },
  "categories": {
    "前端小笔记": {
      "key": "前端小笔记",
      "scope": "categories",
      "path": "/categories/前端小笔记/",
      "pageKeys": [
        "v-a902958a",
        "v-429c9e4a",
        "v-f658b74a",
        "v-0c49a08a",
        "v-33fd7f0a",
        "v-f01d9cca",
        "v-89b7a58a",
        "v-0fc6f4bb",
        "v-b383dd0a",
        "v-a7f7e70a",
        "v-1398ae4a",
        "v-0f6a454a",
        "v-952a5eca",
        "v-41934eca",
        "v-1bf6df4a",
        "v-62db90fb",
        "v-393dd60a",
        "v-02b9ac5b",
        "v-76b4d0bb",
        "v-931ba80a",
        "v-00a1c85b",
        "v-076d6c9b"
      ]
    },
    "问题集中营": {
      "key": "问题集中营",
      "scope": "categories",
      "path": "/categories/问题集中营/",
      "pageKeys": [
        "v-edf9274a"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "categories",
      "path": "/categories/Cookie/",
      "pageKeys": [
        "v-a3c97e0a"
      ]
    },
    "排序": {
      "key": "排序",
      "scope": "categories",
      "path": "/categories/排序/",
      "pageKeys": [
        "v-7cfdb47b"
      ]
    },
    "VUE": {
      "key": "VUE",
      "scope": "categories",
      "path": "/categories/VUE/",
      "pageKeys": [
        "v-eae4854a",
        "v-1eeda59b",
        "v-de5b760a",
        "v-691d7c7b",
        "v-c330a6ca",
        "v-ef10e90a",
        "v-0d2619bb",
        "v-1dddcc7b",
        "v-5c10a91b"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-ac30674a"
      ]
    },
    "Promise": {
      "key": "Promise",
      "scope": "categories",
      "path": "/categories/Promise/",
      "pageKeys": [
        "v-5867f0db"
      ]
    },
    "npm": {
      "key": "npm",
      "scope": "categories",
      "path": "/categories/npm/",
      "pageKeys": [
        "v-2a6d505b",
        "v-0b0ee53b"
      ]
    },
    "组件": {
      "key": "组件",
      "scope": "categories",
      "path": "/categories/组件/",
      "pageKeys": [
        "v-267bf54a"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "categories",
      "path": "/categories/正则/",
      "pageKeys": [
        "v-2fd6558a"
      ]
    },
    "深夜食堂": {
      "key": "深夜食堂",
      "scope": "categories",
      "path": "/categories/深夜食堂/",
      "pageKeys": [
        "v-4bfa42f1"
      ]
    }
  },
  "timeline": {}
}